---
# tasks file for common
- name: set hostname
  become: true
  become_user: root
  command:
    raspi-config nonint do_hostname {{ inventory_hostname }}

- name: Confirm an up-to-date apt cache is on the system
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: update core packages 
  apt:
    name: '*'
    state: latest
  notify: reboot server

# per docs at https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#ensure-iptables-tooling-does-not-use-the-nftables-backend
- name: ensure iptables is using legacy mode binaries
  alternatives:
    name: '{{ item }}'
    path: /usr/sbin/{{ item }}-legacy
  with_items: '{{ iptables_legacy_bins }}'


# https://gist.github.com/alexellis/fdbc90de7691a1b9edb545c17da2d975
- name: add memory cgroup config to /boot/cmdline.txt
  lineinfile:
      path: /boot/cmdline.txt
      line: cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory
  notify: reboot server

# https://medium.com/developingnodes/setting-up-kubernetes-cluster-on-raspberry-pi-15cc44f404b5
- name: "Disable Swap"
  become: true
  become_user: root
  shell: |
    dphys-swapfile swapoff &&
    dphys-swapfile uninstall &&
    update-rc.d dphys-swapfile remove &&
    systemctl disable dphys-swapfile.service

